fraction_training: 1.0
n_cross_val: null
n_player: 4
data_file: ../../data/experiments/pilot_random1_player_round_slim.csv
output_path: ../../data/artificial_humans/ah_1_1_simple
model_name: graph
shuffle_features: [prev_punishments, prev_contributions, prev_common_good, prev_valid]
labels: {}
model_args:
  hidden_size: 5
  add_rnn: False
  add_edge_model: False
  add_global_model: False
  x_encoding:
    - name: prev_contributions
      n_levels: 21
      encoding: numeric
    - name: prev_punishments
      n_levels: 31
      encoding: numeric
    - etype: bool
      name: prev_valid
  u_encoding: []
  y_levels: 21
  y_name: contributions
mask_name: valid
experiment_names: [trail_rounds_2, random_1]
optimizer_args:
  lr: 1.e-3
  weight_decay: 1.e-5
train_args:
  epochs: 2000
  batch_size: 10
  clamp_grad: 1
  eval_period: 10
device: cpu