n_cross_val: 2
fraction_training: 1.0
data_file: ../../data/experiments/pilot_random1_player_round_slim.csv
output_path: ../../data/training/dev
labels: {}
model_name: graph
model_args:
  # y_levels: 21
  # y_name: contributions
  y_levels: 31
  y_name: punishments
  add_rnn: False
  add_edge_model: False
  add_global_model: False
  hidden_size: 10
  x_encoding:
    - name: prev_contributions
      n_levels: 21
      encoding: numeric
    - name: prev_punishments
      n_levels: 31
      encoding: numeric
    - name: prev_valid
      etype: bool
  u_encoding:
    - name: prev_common_good
      norm: 32
      etype: float
    - name: round_number
      n_levels: 16
      encoding: numeric
# mask: valid
mask_name: manager_valid
# experiment_names: [trail_rounds_2, random_1]
experiment_names: [trail_rounds_2]
optimizer_args:
  lr: 1.e-4
  weight_decay: 1.e-5
train_args:
  epochs: 100
  batch_size: 20
  clamp_grad: 1
  eval_period: 10
n_player: 4
shuffle_features:
  - prev_punishments
  - prev_contributions
  - prev_common_good
device: cpu
