fraction_training: 1.0
n_contributions: 21
n_punishments: 31
n_cross_val: null
fraction_training: 1.0
n_player: 4
data_file: ../../data/experiments/pilot_random1_player_round_slim.csv
output_path: ../../data/training/ah_11
model_name: graph
shuffle_features: [prev_punishments, prev_contributions, prev_common_good]
labels: {}
model_args:
  hidden_size: 5
  add_rnn: True
  add_edge_model: True
  add_global_model: False
  x_encoding:
    - name: prev_contributions
      n_levels: 21
      encoding: numeric
    - name: prev_punishments
      n_levels: 31
      encoding: numeric
  u_encoding:
    - name: round_number
      n_levels: 16
      encoding: numeric
    - name: prev_common_good
      norm: 128
      etype: float
optimizer_args:
  lr: 1.e-3
  weight_decay: 1.e-5
train_args:
  epochs: 5000
  batch_size: 10
  clamp_grad: 1
  eval_period: 10
device: cpu