x_encoding:
  - encoding: ordinal
    column: prev_contribution
  - encoding: ordinal
    column: prev_punishment
y_encoding: ordinal
n_contributions: 21
n_punishments: 31
n_cross_val: 10
fraction_training: 1.0
data: ../data/pilot1_player_round_slim.csv
output_path: ../data/dev
labels: {}
model_args:
  n_layers: 1
  hidden_size: null
optimizer_args:
  lr: 1.e-4
  weight_decay: 1.e-5
train_args:
  epochs: 100
  batch_size: 40
  clamp_grad: null
  eval_period: 10
